# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-S-O-eKbUtwOqeVmITzzLSYgiQaZsrwe
"""

pipe_svm=Pipeline([('scaler',PowerTransformer()),
                  ('dimensionality',PCA(n_components=14)),
                  ('classifier',svm.SVC(random_state=0))])